// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1:string):Promise<void>;

export function IconGenerator(arg1:string):Promise<Array<string>>;
