// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dial(arg1) {
  return window['go']['main']['App']['Dial'](arg1);
}

export function Publisher(arg1, arg2) {
  return window['go']['main']['App']['Publisher'](arg1, arg2);
}
